# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WA3cpeP1ovtJwtZN1ZA1n60hlirxBhJE
"""

#Hilken Matthaus 11/01/2025
# Loop para garantir que o usuário insira dois números válidos
while True:
    try:
        # Solicita o primeiro número ao usuário
        numero_a = float(input("Digite o primeiro valor: "))
        # Solicita o segundo número ao usuário
        numero_b = float(input("Digite o segundo valor: "))
        # Se os dois números forem válidos, sai do loop
        break
    except ValueError:
        # Caso o usuário insira um valor inválido (não numérico), exibe mensagem de erro
        print("Entrada inválida. Por favor, digite um número válido.")

# Exibe as opções de operação disponíveis
print("\nVocê digitou os números {:.2f} e {:.2f}. Qual operação deseja executar com esses valores?"
      "\n1: Soma"
      "\n2: Subtração"
      "\n3: Multiplicação"
      "\n4: Divisão\n".format(numero_a, numero_b))

# Loop para garantir que o usuário escolha uma operação válida
while True:
    try:
        # Solicita que o usuário escolha uma operação
        operacao = int(input("Digite o valor correspondente à operação que deseja realizar (1-4): "))
        # Verifica se o número inserido está entre 1 e 4
        if operacao not in [1, 2, 3, 4]:
            # Se não estiver, exibe uma mensagem de erro e continua o loop
            print("Operação inválida. Escolha uma opção entre 1 e 4.")
            continue
        # Sai do loop se uma operação válida for escolhida
        break
    except ValueError:
        # Caso o usuário insira algo que não seja um número inteiro, exibe mensagem de erro
        print("Entrada inválida. Por favor, digite um número inteiro.")

# Bloco condicional para realizar a operação escolhida
if operacao == 1:
    # Soma dos números
    resultado = numero_a + numero_b
    print(f"O resultado da soma é: {resultado:.2f}")
elif operacao == 2:
    # Subtração dos números
    resultado = numero_a - numero_b
    print(f"O resultado da subtração é: {resultado:.2f}")
elif operacao == 3:
    # Multiplicação dos números
    resultado = numero_a * numero_b
    print(f"O resultado da multiplicação é: {resultado:.2f}")
elif operacao == 4:
    # Divisão dos números
    if numero_b == 0:
        # Verifica se o divisor é zero e exibe mensagem de erro, se necessário
        print("Erro: Divisão por zero não é permitida.")
    else:
        # Calcula a divisão se o divisor for diferente de zero
        resultado = numero_a / numero_b
        print(f"O resultado da divisão é: {resultado:.2f}")

